### ISSUE TITLE
Can you provide how to compile a new .so file

### ISSUE THREAD

**Issue by holoword** [rootlu/RHINE#1]

**Comment by rootlu** [comment]
You can refer to https://github.com/thunlp/OpenNE.

**Comment by holoword** [comment]
> You can refer to https://github.com/thunlp/OpenNE.

Maybe you are talking about OpenKE, but sounds like you are change a lot of things or The current version of openke is much different from you are using.
So, can you send me a copy to my e-mail
yehao@pku.edu.cn

I want to use this module as a baseline

**Comment by rootlu** [comment]
Sorry, I mean the OpenKE: https://github.com/thunlp/OpenKE.
I have sent you the C++ files that compile .so file.
