### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by Hanmii** [rootlu/RHINE#2]
hi,can you offer the complete data set? i cant run the code with the given data,thanks.

**Comment by rootlu** [comment]
Hi, what's your problem with the given code and dataset?

**Comment by Hanmii** [comment]
It seems that the given dataset doesn't contain the 'paper_author.txt', 'paper_conf.txt' 'paper_term.txt' .

**Comment by rootlu** [comment]
Hi,

The given datasets have been preprocessed for our model, you can run the code with them directly.
Now we also upload the original dataset in oriData/, please refer to it for detailed dataset.

Thanks for your interest in our work!

**Comment by Hanmii** [comment]
Thanks!

**Comment by A787** [comment]
wen xia shu ju ji 是 dblp v 几？

**Comment by rootlu** [comment]
> wen xia shu ju ji 是 dblp v 几？

Hi, 

This dataset is extracted from https://dblp.uni-trier.de by ourselves.
